[build]
dockerfilePath = "services/alertmanager/Dockerfile"
watchPatterns = ["services/alertmanager/**"]

[deploy]
healthcheckPath = "/-/healthy"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
