apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: Redis-MindsDB
    type: redis-datasource
    access: proxy
    url: redis://redis-mindsdb:6379
    jsonData:
      client: standalone
      password: AraWJNWHvFIZK46p8YGGdypax
    editable: true

  - name: Redis-Sessions
    type: redis-datasource
    access: proxy
    url: redis://redis-sessions:6379
    jsonData:
      client: standalone
      password: XkMkBUxO8jQiRpclznFop7OTQ
    editable: true 